// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"net/http"
	"restful-api/app"
	"restful-api/handler"
	"restful-api/repository"
	"restful-api/service"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitServer() *http.Server {
	categoryRepositoryImpl := repository.NewCategoryRepository()
	db := app.NewDB()
	validate := validator.New()
	categoryServiceImpl := service.NewCategoryService(categoryRepositoryImpl, db, validate)
	categoryHandlerImpl := handler.NewCategoryHandler(categoryServiceImpl)
	router := app.NewRouter(categoryHandlerImpl)
	server := NewServer(router)
	return server
}

// injector.go:

var CategorySet = wire.NewSet(repository.NewCategoryRepository, wire.Bind(new(repository.CategoryRepository), new(*repository.CategoryRepositoryImpl)), service.NewCategoryService, wire.Bind(new(service.CategoryService), new(*service.CategoryServiceImpl)), handler.NewCategoryHandler, wire.Bind(new(handler.CategoryHandler), new(*handler.CategoryHandlerImpl)))
